# VARIAVEIS - 
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}

### GET USER BY EMAIL
@userEmail = jetlee@gmail.com
GET {{host}}/user/{{userEmail}} HTTP/1.1

###


POST {{host}}/user HTTP/1.1
content-type: {{contentType}}

{
    "name": "Jet Lee",
    "email": "jetlee@gmail.com",
    "password": "@Jet123"
}

# SISTEMA DE LOGIN E AUTENTICACAO
### login
POST {{host}}/login HTTP/1.1
content-type: {{contentType}}

{
    "email": "jetlee@gmail.com",
    "password": "@Jet123"
}