# VARIAVEIS - 
@hostname = http://localhost
@port = 3000
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsImVtYWlsIjoiamV0bGVlQGdtYWlsLmNvbSIsIm5hbWUiOiJKZXQgTGVlIiwiaWF0IjoxNzM5NDk0MzM1LCJleHAiOjE3NDAwOTkxMzV9.k-4POXHtswKf30vguuJgJ4jcnyDI9n-1aERH8Z137M4
@authorization = Bearer {{token}}

### GET USER BY EMAIL
@userEmail = jetlee@gmail.com
GET {{host}}/user/{{userEmail}} HTTP/1.1
Authorization: {{authorization}}

### GET USER LOGGED
GET {{host}}/me HTTP/1.1
Authorization: {{authorization}}

###
POST {{host}}/user HTTP/1.1
content-type: {{contentType}}
Authorization: {{authorization}}

{
    "name": "Bruce Lee",
    "email": "brucelee@gmail.com",
    "password": "@Bruce123"
}

# MODULO DE LOGIN E AUTENTICACAO
### login
POST {{host}}/login HTTP/1.1
content-type: {{contentType}}

{
    "email": "brucelee@gmail.com",
    "password": "@Bruce123"
}

# MODULO DE ACCOUNT
### GET ALL ACCOUNT
GET {{host}}/account HTTP/1.1
Authorization: {{authorization}}

### GET ACCOUNT BY ID
GET {{host}}/account/831a3342-ae77-4656-9682-68833b3e4c2c HTTP/1.1
Authorization: {{authorization}}

### GET ACCOUNT BY NAME
GET {{host}}/account/name/contaBruce HTTP/1.1
Authorization: {{authorization}}

### CREATE ACCOUNT
POST {{host}}/account HTTP/1.1
content-type: {{contentType}}
Authorization: {{authorization}}

{
    "name": "contaBruce",
    "balance": 0,
    "user": {
                "id": 1,
                "email": "jetlee@gmail.com",
                "name": "Jet Lee"
            }
}

### UPDATE ACCOUNT
PATCH {{host}}/account/831a3342-ae77-4656-9682-68833b3e4c2c HTTP/1.1
content-type: {{contentType}}
Authorization: {{authorization}}

{
    "name": "contaBruceNOVA"
}

### REMOVE ACCOUNT
DELETE {{host}}/account/831a3342-ae77-4656-9682-68833b3e4c2c HTTP/1.1
content-type: {{contentType}}
Authorization: {{authorization}}

